-- DB-BASE-01 system permission seed data.
-- Source: docs/goals/DB-BASE-01.md Appendix A.
-- This file inserts only roles, permissions, and role-permission relationships.

START TRANSACTION;

INSERT INTO sys_role (
    role_code,
    role_name,
    risk_level,
    description,
    status,
    is_builtin
) VALUES
    ('SYSTEM_ADMIN', '系统管理员', 'HIGH', '维护Demo用户、角色和技术配置；不自动获得业务高风险权限', 'ACTIVE', 1),
    ('PURCHASER', '采购员', 'NORMAL', '维护采购侧资料、首营申请和采购订单', 'ACTIVE', 1),
    ('RECEIVER', '收货员', 'NORMAL', '登记到货并形成待验批次', 'ACTIVE', 1),
    ('ACCEPTANCE_INSPECTOR', '验收员', 'HIGH', '逐批验收并提交质量结论', 'ACTIVE', 1),
    ('QUALITY_MANAGER', '质量管理员', 'HIGH', '质量审核、调查和处置建议', 'ACTIVE', 1),
    ('QUALITY_HEAD', '质量负责人', 'HIGH', '首营和重大质量处置最终批准', 'ACTIVE', 1),
    ('WAREHOUSE_OPERATOR', '仓库管理员', 'NORMAL', '入库、库存作业、备货、发运和签收', 'ACTIVE', 1),
    ('SALES_OPERATOR', '销售员', 'NORMAL', '客户资料、销售订单和库存占用申请', 'ACTIVE', 1),
    ('OUTBOUND_REVIEWER', '出库复核员', 'HIGH', '独立复核并触发出库', 'ACTIVE', 1),
    ('AUDIT_VIEWER', '审计查看员', 'HIGH', '只读审计、追溯和任务执行证据', 'ACTIVE', 1);

INSERT INTO sys_permission (
    permission_code,
    module_code,
    permission_name,
    execution_mode,
    is_builtin
) VALUES
    ('SYS-001', 'SYS', '查看本人账号与角色', 'ROLE', 1),
    ('SYS-002', 'SYS', '创建演示用户', 'ROLE', 1),
    ('SYS-003', 'SYS', '启用、停用用户', 'ROLE', 1),
    ('SYS-004', 'SYS', '重置用户密码', 'ROLE', 1),
    ('SYS-005', 'SYS', '提交角色分配申请', 'ROLE', 1),
    ('SYS-006', 'SYS', '审核业务角色权限', 'ROLE', 1),
    ('SYS-007', 'SYS', '批准高风险角色分配', 'ROLE', 1),
    ('SYS-008', 'SYS', '技术执行角色分配', 'ROLE', 1),
    ('SYS-009', 'SYS', '查看权限目录', 'ROLE', 1),
    ('SYS-010', 'SYS', '修改权限目录', 'NOT_OPEN', 1),
    ('SYS-011', 'SYS', '查看审计日志', 'ROLE', 1),
    ('SYS-012', 'SYS', '修改或删除审计日志', 'PROHIBITED', 1),
    ('SYS-013', 'SYS', '切换NATIONAL_DEFAULT / GD_DEMO_PROFILE', 'ROLE', 1),
    ('SYS-014', 'SYS', '修改关键质量控制配置', 'ROLE', 1),
    ('SYS-015', 'SYS', '查看系统健康和版本', 'ROLE', 1),
    ('SYS-016', 'SYS', '查看本人操作日志', 'ROLE', 1),
    ('MD-001', 'MD', '创建药品档案草稿', 'ROLE', 1),
    ('MD-002', 'MD', '编辑药品档案草稿或待完善资料', 'ROLE', 1),
    ('MD-003', 'MD', '完成药品档案资料检查', 'ROLE', 1),
    ('MD-004', 'MD', '启用或停用药品档案', 'ROLE', 1),
    ('MD-005', 'MD', '创建供应商资料草稿', 'ROLE', 1),
    ('MD-006', 'MD', '编辑供应商未审核资料', 'ROLE', 1),
    ('MD-007', 'MD', '查看供应商完整资质', 'ROLE', 1),
    ('MD-008', 'MD', '创建客户资料草稿', 'ROLE', 1),
    ('MD-009', 'MD', '编辑客户未审核资料', 'ROLE', 1),
    ('MD-010', 'MD', '查看客户资质', 'ROLE', 1),
    ('MD-011', 'MD', '删除已提交或已使用的基础档案', 'PROHIBITED', 1),
    ('QA-001', 'QA', '创建首营企业申请', 'ROLE', 1),
    ('QA-002', 'QA', '提交首营企业审核', 'ROLE', 1),
    ('QA-003', 'QA', '撤回本人未处理申请', 'ROLE', 1),
    ('QA-004', 'QA', '审核首营企业', 'ROLE', 1),
    ('QA-005', 'QA', '批准或驳回首营企业', 'ROLE', 1),
    ('QA-006', 'QA', '标记首营企业失效', 'ROLE_AND_SYSTEM', 1),
    ('QA-007', 'QA', '创建首营品种申请', 'ROLE', 1),
    ('QA-008', 'QA', '审核首营品种', 'ROLE', 1),
    ('QA-009', 'QA', '批准或驳回首营品种', 'ROLE', 1),
    ('QA-010', 'QA', '失效或触发重新审核首营品种', 'ROLE_AND_SYSTEM', 1),
    ('QA-011', 'QA', '提交客户资质审核', 'ROLE', 1),
    ('QA-012', 'QA', '审核客户合法性、范围和人员资格', 'ROLE', 1),
    ('QA-013', 'QA', '冻结客户', 'ROLE', 1),
    ('QA-014', 'QA', '解除客户冻结', 'ROLE', 1),
    ('QA-015', 'QA', '系统执行资质到期失效', 'ROLE_AND_SYSTEM', 1),
    ('QA-016', 'QA', '查看质量审批完整意见', 'ROLE', 1),
    ('PO-001', 'PO', '创建采购订单草稿', 'ROLE', 1),
    ('PO-002', 'PO', '编辑采购订单草稿', 'ROLE', 1),
    ('PO-003', 'PO', '确认采购订单', 'ROLE', 1),
    ('PO-004', 'PO', '关闭未确认草稿', 'ROLE', 1),
    ('PO-005', 'PO', '受控关闭已确认未收货订单', 'ROLE', 1),
    ('PO-006', 'PO', '终止部分收货后的未收数量', 'ROLE', 1),
    ('PO-007', 'PO', '修改已确认订单核心数据', 'PROHIBITED', 1),
    ('PO-008', 'PO', '查看采购订单', 'ROLE', 1),
    ('PO-009', 'PO', '删除采购订单', 'PROHIBITED', 1),
    ('RC-001', 'RC', '创建收货记录', 'ROLE', 1),
    ('RC-002', 'RC', '开始收货', 'ROLE', 1),
    ('RC-003', 'RC', '登记到货、包装、运输和随货异常', 'ROLE', 1),
    ('RC-004', 'RC', '处理一般收货差异', 'ROLE', 1),
    ('RC-005', 'RC', '完成收货', 'ROLE', 1),
    ('RC-006', 'RC', '生成待验批次', 'ROLE_AND_SYSTEM', 1),
    ('RC-007', 'RC', '取消未进入验收的收货记录', 'ROLE', 1),
    ('RC-008', 'RC', '修改已进入验收的收货记录', 'PROHIBITED', 1),
    ('RC-009', 'RC', '作出质量合格或不合格结论', 'ROLE', 1),
    ('ACPT-001', 'ACPT', '查看待验批次和相关资料', 'ROLE', 1),
    ('ACPT-002', 'ACPT', '开始逐批验收', 'ROLE', 1),
    ('ACPT-003', 'ACPT', '录入验收检查项和数量', 'ROLE', 1),
    ('ACPT-004', 'ACPT', '提交质量介入', 'ROLE', 1),
    ('ACPT-005', 'ACPT', '给出质量处理意见并退回验收', 'ROLE', 1),
    ('ACPT-006', 'ACPT', '提交合格结论', 'ROLE', 1),
    ('ACPT-007', 'ACPT', '提交部分合格结论', 'ROLE', 1),
    ('ACPT-008', 'ACPT', '提交不合格结论', 'ROLE', 1),
    ('ACPT-009', 'ACPT', '修改已完成验收结论', 'ROLE', 1),
    ('ACPT-010', 'ACPT', '删除验收记录', 'PROHIBITED', 1),
    ('INV-001', 'INV', '查看批号库存、质量结论和冻结摘要', 'ROLE', 1),
    ('INV-002', 'INV', '指定或确认入库库位', 'ROLE', 1),
    ('INV-003', 'INV', '根据合格验收确认入库', 'ROLE_AND_SYSTEM', 1),
    ('INV-004', 'INV', '自动生成入库库存流水', 'SYSTEM', 1),
    ('INV-005', 'INV', '直接修改库存总数', 'PROHIBITED', 1),
    ('INV-006', 'INV', '发起人工库存数量调整', 'NOT_OPEN', 1),
    ('INV-007', 'INV', '审核人工库存数量调整', 'NOT_OPEN', 1),
    ('INV-008', 'INV', '批准人工库存数量调整', 'NOT_OPEN', 1),
    ('INV-009', 'INV', '查看库存流水和质量历史', 'ROLE', 1),
    ('INV-010', 'INV', '修改或删除库存流水', 'PROHIBITED', 1),
    ('INV-011', 'INV', '系统识别过期并阻断', 'SYSTEM', 1),
    ('INV-012', 'INV', '恢复不合格或过期为合格', 'PROHIBITED', 1),
    ('SO-001', 'SO', '创建销售订单草稿', 'ROLE', 1),
    ('SO-002', 'SO', '编辑销售订单草稿', 'ROLE', 1),
    ('SO-003', 'SO', '提交客户校验', 'ROLE', 1),
    ('SO-004', 'SO', '自动执行客户和范围校验', 'ROLE_AND_SYSTEM', 1),
    ('SO-005', 'SO', '处理客户校验例外', 'ROLE', 1),
    ('SO-006', 'SO', '进入批次分配', 'ROLE', 1),
    ('SO-007', 'SO', '选择候选批次', 'ROLE', 1),
    ('SO-008', 'SO', '创建库存占用', 'ROLE_AND_SYSTEM', 1),
    ('SO-009', 'SO', '释放占用', 'ROLE_AND_SYSTEM', 1),
    ('SO-010', 'SO', '关闭草稿或已确认订单', 'ROLE', 1),
    ('SO-011', 'SO', '关闭已分配批次订单', 'ROLE', 1),
    ('SO-012', 'SO', '修改已进入出库复核的核心数据', 'PROHIBITED', 1),
    ('SO-013', 'SO', '质量冻结阻断已有占用', 'SYSTEM', 1),
    ('SO-014', 'SO', '质量阻断后退回重新分配', 'ROLE_AND_SYSTEM', 1),
    ('OUT-001', 'OUT', '备货并提交复核', 'ROLE', 1),
    ('OUT-002', 'OUT', '开始出库复核', 'ROLE', 1),
    ('OUT-003', 'OUT', '提交复核不通过', 'ROLE', 1),
    ('OUT-004', 'OUT', '提交复核通过', 'ROLE', 1),
    ('OUT-005', 'OUT', '执行实际出库和库存扣减', 'ROLE_AND_SYSTEM', 1),
    ('OUT-006', 'OUT', '复核失败后纠正并重新提交', 'ROLE', 1),
    ('OUT-007', 'OUT', '创建发运记录', 'ROLE', 1),
    ('OUT-008', 'OUT', '登记签收或到货确认', 'ROLE', 1),
    ('OUT-009', 'OUT', '登记运输异常', 'ROLE', 1),
    ('OUT-010', 'OUT', '调查并处理运输质量异常', 'ROLE', 1),
    ('OUT-011', 'OUT', '受控更正已出库、发运或签收记录', 'ROLE', 1),
    ('OUT-012', 'OUT', '删除出库、复核、发运或签收记录', 'PROHIBITED', 1),
    ('TRACE-001', 'TRACE', '查询批号全过程追溯', 'ROLE', 1),
    ('TRACE-002', 'TRACE', '查看质量事件和冻结处置', 'ROLE', 1),
    ('TRACE-003', 'TRACE', '查看客户去向', 'ROLE', 1),
    ('TRACE-004', 'TRACE', '导出完整追溯证据', 'ROLE', 1),
    ('TRACE-005', 'TRACE', '修改追溯查询结果', 'PROHIBITED', 1),
    ('TRACE-006', 'TRACE', '标记链路不完整并发起调查', 'ROLE', 1),
    ('QE-001', 'QE', '创建正式质量事件', 'ROLE', 1),
    ('QE-002', 'QE', '紧急冻结受影响库存', 'ROLE', 1),
    ('QE-003', 'QE', '扩大或缩小影响范围', 'ROLE', 1),
    ('QE-004', 'QE', '开始或继续调查质量事件', 'ROLE', 1),
    ('QE-005', 'QE', '提交解除冻结处置建议', 'ROLE', 1),
    ('QE-006', 'QE', '提交转不合格处置建议', 'ROLE', 1),
    ('QE-007', 'QE', '批准解除冻结', 'ROLE', 1),
    ('QE-008', 'QE', '批准转不合格', 'ROLE', 1),
    ('QE-009', 'QE', '退回质量调查', 'ROLE', 1),
    ('QE-010', 'QE', '执行批准后的处置', 'ROLE_AND_SYSTEM', 1),
    ('QE-011', 'QE', '关闭质量事件', 'ROLE', 1),
    ('QE-012', 'QE', '取消误建质量事件', 'ROLE', 1),
    ('QE-013', 'QE', '删除质量事件、动作或冻结历史', 'PROHIBITED', 1),
    ('GD-001', 'GD', '创建入库码核验事件并扫描或录入', 'ROLE', 1),
    ('GD-002', 'GD', '创建出库码核验事件并扫描', 'ROLE', 1),
    ('GD-003', 'GD', '自动执行重复码和一致性核验', 'SYSTEM', 1),
    ('GD-004', 'GD', '纠正来源数据并重新提交核验', 'ROLE', 1),
    ('GD-005', 'GD', '作废未有效使用的演示追溯码', 'ROLE', 1),
    ('GD-006', 'GD', '直接将核验失败改为核验通过', 'PROHIBITED', 1),
    ('GD-007', 'GD', '重新使用已作废追溯码', 'PROHIBITED', 1),
    ('GD-008', 'GD', '生成 Mock 交换任务', 'SYSTEM', 1),
    ('GD-009', 'GD', '执行 Mock 上传', 'ROLE_AND_SYSTEM', 1),
    ('GD-010', 'GD', '保存 Mock 成功回执', 'SYSTEM', 1),
    ('GD-011', 'GD', '保存 Mock 失败或超时', 'SYSTEM', 1),
    ('GD-012', 'GD', '标记失败任务待重试', 'ROLE_AND_SYSTEM', 1),
    ('GD-013', 'GD', '执行重试', 'ROLE_AND_SYSTEM', 1),
    ('GD-014', 'GD', '终止 Mock 交换任务', 'ROLE', 1),
    ('GD-015', 'GD', '将 Mock 失败人工改为成功', 'PROHIBITED', 1),
    ('GD-016', 'GD', '将 Mock 成功描述为真实监管成功', 'PROHIBITED', 1),
    ('GD-017', 'GD', '已终止任务继续上传或重试', 'PROHIBITED', 1),
    ('DEMO-001', 'DEMO', '查看演示数据任务', 'ROLE', 1),
    ('DEMO-002', 'DEMO', '执行演示数据初始化', 'ROLE', 1),
    ('DEMO-003', 'DEMO', '执行演示数据重置', 'ROLE', 1),
    ('DEMO-004', 'DEMO', '在非 Demo 环境执行重置', 'PROHIBITED', 1),
    ('DEMO-005', 'DEMO', '手工改库伪造初始化成功', 'PROHIBITED', 1),
    ('BAK-001', 'BAK', '查看备份计划和执行记录', 'ROLE', 1),
    ('BAK-002', 'BAK', '创建或修改 Demo 备份计划', 'ROLE', 1),
    ('BAK-003', 'BAK', '执行备份', 'ROLE_AND_SYSTEM', 1),
    ('BAK-004', 'BAK', '创建恢复验证任务', 'ROLE', 1),
    ('BAK-005', 'BAK', '执行隔离恢复', 'ROLE', 1),
    ('BAK-006', 'BAK', '核对恢复后的关键业务链', 'ROLE', 1),
    ('BAK-007', 'BAK', '标记验证成功', 'ROLE_AND_SYSTEM', 1),
    ('BAK-008', 'BAK', '记录恢复失败', 'ROLE_AND_SYSTEM', 1),
    ('BAK-009', 'BAK', '删除备份失败或恢复失败记录', 'PROHIBITED', 1),
    ('BAK-010', 'BAK', '备份失败后直接进入恢复验证', 'PROHIBITED', 1);

INSERT INTO sys_role_permission (
    role_id,
    permission_id,
    source_matrix_version
) VALUES
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-013'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-013'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-015'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-015'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'SYS-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'MD-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-012'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-013'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-015'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'QA-016'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'PO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'RC-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'ACPT-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'INV-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'SO-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'OUT-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'PURCHASER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'TRACE-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SALES_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-008'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-010'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_HEAD'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-011'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'QE-012'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'WAREHOUSE_OPERATOR'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'RECEIVER'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'ACCEPTANCE_INSPECTOR'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'OUTBOUND_REVIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-009'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-012'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-012'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-013'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'GD-014'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'DEMO-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'DEMO-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'DEMO-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'DEMO-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'DEMO-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-001'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-002'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-003'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-004'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-005'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-006'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'QUALITY_MANAGER'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'AUDIT_VIEWER'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-007'), 'v1.1'),
    ((SELECT id FROM sys_role WHERE role_code = 'SYSTEM_ADMIN'), (SELECT id FROM sys_permission WHERE permission_code = 'BAK-008'), 'v1.1');

COMMIT;
