export const PERMISSIONS = {
  SYS_USER_READ: 'SYS_USER_READ',
  SYS_USER_WRITE: 'SYS_USER_WRITE',
  SYS_USER_STATUS: 'SYS_USER_STATUS',
  SYS_USER_ROLE_ASSIGN: 'SYS_USER_ROLE_ASSIGN',
  SYS_ROLE_READ: 'SYS_ROLE_READ',
  SYS_ROLE_WRITE: 'SYS_ROLE_WRITE',
  SYS_ROLE_PERMISSION_ASSIGN: 'SYS_ROLE_PERMISSION_ASSIGN',
  SYS_PERMISSION_READ: 'SYS_PERMISSION_READ',
  SYS_PERMISSION_WRITE: 'SYS_PERMISSION_WRITE',
  SUPPLIER_READ: 'SUPPLIER_READ',
  SUPPLIER_WRITE: 'SUPPLIER_WRITE',
  SUPPLIER_SUBMIT: 'SUPPLIER_SUBMIT',
  SUPPLIER_REVIEW: 'SUPPLIER_REVIEW',
  TRACE_READ: 'TRACE_READ',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
